version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
    env_file: ../secrets/concourse-db.env
    volumes:
      - /Users/pwall/data/concourse-db:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    image: concourse/concourse
    command: web
    links: [db]
    depends_on: [db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_EXTERNAL_URL: http://wallserver.local:8080
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_DATABASE: concourse
    env_file: ../secrets/concourse-web.env
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [web]
    volumes: ["./keys/worker:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
