version: '3'
services:
  ddclient:
    image: linuxserver/ddclient
    restart: unless-stopped
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Chicago
    volumes:
      - ../secrets/ddclient.conf:/config/ddclient.conf
    restart: unless-stopped

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.ci.petewall.net.conf:/etc/nginx/conf.d/nginx.ci.petewall.net.conf
      - ../secrets/certbot/conf:/etc/letsencrypt
      - ../secrets/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    links: [web]
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ../secrets/certbot/conf:/etc/letsencrypt
      - ../secrets/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: concourse
    env_file: ../secrets/concourse-db.env
    volumes:
      - /Users/pwall/data/concourse-db:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    image: concourse/concourse
    restart: unless-stopped
    command: web
    links: [db]
    depends_on: [db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_EXTERNAL_URL: http://ci.petewall.net
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_DATABASE: concourse
    env_file: ../secrets/concourse-web.env
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker:
    image: concourse/concourse
    restart: unless-stopped
    command: worker
    privileged: true
    depends_on: [web]
    volumes: ["./keys/worker:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
