resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/wallhouse-bridge.git
      branch: master
      ignore_paths:
        - ci/*
        - ci/**
      private_key: ((github-repo-key))

  - name: image
    type: docker-image
    icon: docker
    source:
      repository: petewall/bridge
      username: ((dockerhub-username))
      password: ((dockerhub-password))

  - name: feature-test-image-source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/wallhouse-bridge.git
      branch: master
      paths:
        - ci/*
        - ci/**
      private_key: ((github-repo-key))

  - name: feature-test-image
    type: docker-image
    icon: docker
    source:
      repository: petewall/bridge-test
      username: ((dockerhub-username))
      password: ((dockerhub-password))

  - name: pull-requests
    type: pull-request
    source:
      repository: petewall/wallhouse-bridge
      access_token: ((github-access-token))

jobs:
  - name: build-feature-test-image
    plan:
      - get: feature-test-image-source
        trigger: true
      - put: feature-test-image
        params:
          build: feature-test-image-source/ci

  - name: build-image
    plan: 
      - in_parallel:
        - get: feature-test-image
          passed:
            - build-feature-test-image
        - get: source
          trigger: true
      - task: deps
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: slim
          inputs:
            - name: source
          outputs:
            - name: source
          run:
            dir: source
            path: npm
            args: [install]
      - task: test
        image: feature-test-image
        config:
          platform: linux
          inputs:
            - name: source
          params:
            DEBUG: "*"
          run:
            dir: source
            path: npm
            args: [test]
      - put: image
        params:
          build: source

  - name: test-pull-request
    plan:
      - get: feature-test-image
        passed:
          - build-feature-test-image
      - get: source
        resource: pull-requests
        trigger: true
        version: every
        params:
          integration_tool: rebase
      - put: pull-requests
        params:
          path: source
          status: pending
      - do:
        - task: deps
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: node
                tag: slim
            inputs:
              - name: source
            outputs:
              - name: source
            run:
              dir: source
              path: npm
              args: [install]
        - task: test
          image: feature-test-image
          config:
            platform: linux
            inputs:
              - name: source
            params:
              DEBUG: "*"
            run:
              dir: source
              path: npm
              args: [test]
        on_failure:
          put: pull-requests
          params:
            path: source
            status: failure
      - put: pull-requests
        params:
          path: source
          status: success
