resources:
  - name: source
    type: git
    source:
      url: git@github.com:petewall/wallhouse-bridge.git
      branch: master

jobs:
  - name: test
    plan: 
      - get: source
        trigger: true
      - task: unit-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: slim
          inputs:
            - name: source
          run:
            dir: source
            path: npm
            args: [test]
