resources:
  - name: source
    type: git
    icon: github
    source:
      uri: git@github.com:petewall/circuit-finder.git
      private_key: ((github-repo-key))

jobs:
  - name: test
    plan:
      - get: source
        trigger: true
      - task: get-deps
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: slim
          inputs:
            - name: source
          run:
            path: yarn
            dir: source/test/client
            args: [ --emoji, true ]
          outputs:
            - name: source
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: slim
          inputs:
            - name: source
          run:
            path: yarn
            dir: source/test/client
            args: [ --emoji, true, test ]
