resource_types:
  - name: pypi
    type: docker-image
    source:
      repository: punkadiddle/concourse-pypi-resource
      tag: latest-rc

resources:
  - name: bootloader-source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/wallhouse-device-wemos-d1-mini.git
      branch: master
      private_key: ((github-repo-key))
      ignore_paths:
        - ci/*
        - ci/**
        - lib/TempSensor/*
        - src/firmware/temperature.cpp

  - name: temperature-sensor-source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/wallhouse-device-wemos-d1-mini.git
      branch: master
      private_key: ((github-repo-key))
      ignore_paths:
        - ci/*
        - ci/**
        - lib/Blinker/*
        - src/firmware/bootloader.cpp

  - name: ota-source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/wallhouse-ota-service.git
      branch: master
      paths:
        - ci/*
        - ci/**
      private_key: ((github-repo-key))

  - name: bootloader-version
    type: semver
    source:
      driver: git
      uri: git@github.com:petewall/versions.git
      branch: master
      file: firmware-bootloader
      private_key: ((github-repo-key))

  - name: office-version
    type: semver
    source:
      driver: git
      uri: git@github.com:petewall/versions.git
      branch: master
      file: firmware-office
      private_key: ((github-repo-key))

  - name: platformio
    type: docker-image
    icon: docker
    source:
      repository: petewall/platformio
      username: ((dockerhub-username))
      password: ((dockerhub-password))

  - name: platformio-package
    type: pypi
    icon: language-python
    source:
      name: platformio

  - name: platformio-source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/platformio-docker
      branch: master
      private_key: ((github-repo-key))

jobs:
  - name: build-platformio
    plan:
      - in_parallel:
        - get: platformio-package
          trigger: true
        - get: platformio-source
          trigger: true
      - put: platformio
        params:
          build: platformio-source

  - name: build-bootloader
    plan:
      - in_parallel:
        - get: version
          resource: bootloader-version
          params:
            bump: patch
        - get: source
          resource: bootloader-source
          trigger: true
        - get: ota-source
        - get: platformio
          passed:
            - build-platformio
      - task: check
        image: platformio
        config:
          platform: linux
          inputs:
            - name: source
          run:
            dir: source
            path: pio
            args: ["check", "--environment", "d1_mini_bootloader"]
      - task: build
        image: platformio
        file: source/ci/tasks/build.yml
        params:
          FIRMWARE_TYPE: d1_mini_bootloader
          OTA_HOST: http://wallserver.local:8266
          WIFI_SSID: ((wifi-ssid))
          WIFI_PASSWORD: ((wifi-password))
      - task: firmware-upload
        file: ota-source/ci/tasks/upload.yml
        params:
          OTA_SERVICE: http://wallserver.local:8266
          TYPE: d1_mini_bootloader
      - put: bootloader-version
        params:
          file: version/version

  - name: build-office-firmware
    plan:
      - in_parallel:
        - get: version
          resource: office-version
          params:
            bump: patch
        - get: source
          resource: temperature-sensor-source
          trigger: true
        - get: ota-source
        - get: platformio
          passed:
            - build-platformio
      - task: check
        image: platformio
        config:
          platform: linux
          inputs:
            - name: source
          run:
            dir: source
            path: pio
            args: ["check", "--environment", "d1_mini_office"]
      - task: build
        image: platformio
        file: source/ci/tasks/build.yml
        params:
          DEVICE_ID: office
          FIRMWARE_TYPE: d1_mini_office
          MQTT_HOSTNAME: wallserver.local
          MQTT_PASSWORD: ((device-office-mqtt-password))
          OTA_HOST: http://wallserver.local:8266
          WIFI_SSID: ((wifi-ssid))
          WIFI_PASSWORD: ((wifi-password))
      - task: firmware-upload
        file: ota-source/ci/tasks/upload.yml
        params:
          OTA_SERVICE: http://wallserver.local:8266
          TYPE: d1_mini_office
      - put: office-version
        params:
          file: version/version
