resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: reportable-source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/wallhouse-device-reportable.git
      branch: master
      private_key: ((github-repo-key))

  - name: reportable-image
    type: docker-image
    icon: docker
    source:
      repository: petewall/reportable
      username: ((dockerhub-username))
      password: ((dockerhub-password))

  - name: reportable-pull-requests
    type: pull-request
    source:
      repository: petewall/wallhouse-device-reportable
      access_token: ((github-access-token))

jobs:
  - name: test-reportable
    plan:
      - get: source
        resource: reportable-source
        trigger: true
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: 1.14
          inputs:
            - name: source
          run:
            dir: source
            path: make
            args: [test]

  - name: build-reportable-image
    plan:
      - get: reportable-source
        passed:
          - test-reportable
        trigger: true
      - put: reportable-image
        params:
          build: source

  - name: test-reportable-pull-request
    plan:
      - get: source
        resource: reportable-pull-requests
        trigger: true
        version: every
        params:
          integration_tool: rebase
      - put: reportable-pull-requests
        params:
          path: source
          status: pending

      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: 1.14
          inputs:
            - name: source
          run:
            dir: source
            path: make
            args: [test]
        on_failure:
          put: reportable-pull-requests
          params:
            path: source
            status: failure
      - put: reportable-pull-requests
        params:
          path: source
          status: success
