resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/eink-radiator.git
      branch: master
      private_key: ((github-repo-key))

  - name: image
    type: docker-image
    icon: docker
    source:
      repository: petewall/eink-radiator
      username: ((dockerhub-username))
      password: ((dockerhub-password))

  - name: pull-requests
    type: pull-request
    source:
      repository: petewall/wallhouse-ota-service
      access_token: ((github-access-token))

jobs:
  - name: test
    plan:
      - get: source
        trigger: true
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: 3.7
          inputs:
            - name: source
          run:
            dir: source
            path: make
            args: [test]

  - name: build-image
    plan:
      - get: source
        trigger: true
        passed:
          - test
      - put: image
        params:
          build: source
          cache: true


  - name: test-pull-request
    plan:
      - get: source
        resource: pull-requests
        trigger: true
        version: every
        params:
          integration_tool: rebase
      - put: pull-requests
        params:
          path: source
          status: pending

      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: 3.7
          inputs:
            - name: source
          run:
            dir: source
            path: make
            args: [test]
        on_failure:
          put: pull-requests
          params:
            path: source
            status: failure
      - put: pull-requests
        params:
          path: source
          status: success
