resources:
  - name: source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/eink-radiator.git
      branch: master
      private_key: ((github-repo-key))

  - name: image
    type: docker-image
    icon: docker
    source:
      repository: petewall/eink-radiator
      username: ((dockerhub-username))
      password: ((dockerhub-password))

jobs:
  - name: build-image
    plan:
      - get: source
        trigger: true
      - put: image
        params:
          build: source
