resources:
  - name: source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/eink-radiator.git
      branch: master
      private_key: ((github-repo-key))

  - name: image
    type: docker-image
    icon: docker
    source:
      repository: petewall/eink-radiator
      username: ((dockerhub-username))
      password: ((dockerhub-password))

jobs:
  - name: test
    plan:
      - get: source
        trigger: true
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: 3.7
          inputs:
            - name: source
          run:
            dir: source
            path: make
            args: [test]

  - name: build-image
    plan:
      - get: source
        trigger: true
        passed:
          - test
      - put: image
        params:
          build: source
