resources:
  - name: source
    type: git
    source:
      uri: git@github.com:petewall/wallhouse-ota-service.git
      branch: master
      private_key: ((github-repo-key))

jobs:
  - name: test
    plan: 
      - get: source
        trigger: true
      - task: deps
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: slim
          inputs:
            - name: source
          outputs:
            - name: source
          run:
            dir: source
            path: npm
            args: [install]
      - task: lint
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: slim
          inputs:
            - name: source
          run:
            dir: source
            path: npm
            args: [lint]
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: slim
          inputs:
            - name: source
          params:
            CI: true
          run:
            dir: source
            path: npm
            args: [test]
