resource_types:
  - name: pypi
    type: docker-image
    source:
      repository: punkadiddle/concourse-pypi-resource
      tag: latest-rc

resources:
  - name: platformio-package
    type: pypi
    source:
      name: platformio

  - name: source
    type: git
    source:
      uri: git@github.com:petewall/platformio-docker
      branch: master
      private_key: ((github-repo-key))

  - name: image
    type: docker-image
    source:
      repository: petewall/platformio
      username: ((dockerhub-username))
      password: ((dockerhub-password))

jobs:
  - name: build-image
    plan:
      - in_parallel:
        - get: platformio-package
          trigger: true
        - get: source
          trigger: true
      - put: image
        params:
          build: source
