resources:
  - name: source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/wallhouse-radio-sensor.git
      branch: master
      private_key: ((github-repo-key))

  - name: rtlamr
    type: github-release
    source:
      owner: bemasher
      repository: rtlamr

  - name: image
    type: docker-image
    icon: docker
    source:
      repository: petewall/radio-sensor
      username: ((dockerhub-username))
      password: ((dockerhub-password))

jobs:
  - name: build-image
    plan:
      - get: source
        trigger: true
      - get: rtlamr
      - put: image
        params:
          build: source
          build_args:
            TIMEZONE: America/Chicago
