resources:
  - name: dht22-sensor-source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/wallhouse-sensors.git
      branch: master
      private_key: ((github-repo-key))
      paths:
        - dht22-sensor/*
        - dht22-sensor/**

  - name: mcp3008-device-source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/wallhouse-sensors.git
      branch: master
      private_key: ((github-repo-key))
      paths:
        - mcp3008-device/*
        - mcp3008-device/**

  - name: radio-sensor-source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/wallhouse-sensors.git
      branch: master
      private_key: ((github-repo-key))
      paths:
        - radio-sensor/*
        - radio-sensor/**

  - name: dht22-sensor
    type: docker-image
    icon: docker
    source:
      repository: petewall/dht22-sensor
      username: ((dockerhub-username))
      password: ((dockerhub-password))

  - name: mcp3008-device
    type: docker-image
    icon: docker
    source:
      repository: petewall/mcp3008-device
      username: ((dockerhub-username))
      password: ((dockerhub-password))

  - name: radio-sensor
    type: docker-image
    icon: docker
    source:
      repository: petewall/radio-sensor
      username: ((dockerhub-username))
      password: ((dockerhub-password))

jobs:
  - name: build-dht22-sensor
    plan:
      - get: source
        resource: dht22-sensor-source
        trigger: true
      - put: dht22-sensor
        params:
          build: source/dht22-sensor
          build_args:
            TIMEZONE: America/Chicago

  - name: build-mcp3008-device
    plan:
      - get: source
        resource: mcp3008-device-source
        trigger: true
      - put: mcp3008-device
        params:
          build: source/mcp3008-device
          build_args:
            TIMEZONE: America/Chicago

  - name: build-radio-sensor
    plan:
      - get: source
        resource: radio-sensor-source
        trigger: true
      - put: radio-sensor
        params:
          build: source/radio-sensor
          build_args:
            TIMEZONE: America/Chicago
