resources:
  - name: source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/wallhouse-service-deployer.git
      branch: master
      private_key: ((github-repo-key))

  - name: image
    type: docker-image
    icon: docker
    source:
      repository: petewall/service-deployer
      username: ((dockerhub-username))
      password: ((dockerhub-password))

jobs:
  - name: build-image
    plan: 
      - get: source
        trigger: true
      # - task: deps
      #   config:
      #     platform: linux
      #     image_resource:
      #       type: docker-image
      #       source:
      #         repository: node
      #         tag: slim
      #     inputs:
      #       - name: source
      #     outputs:
      #       - name: source
      #     run:
      #       dir: source
      #       path: npm
      #       args: [install]
      # - task: test
      #   image: feature-test-image
      #   config:
      #     platform: linux
      #     inputs:
      #       - name: source
      #     params:
      #       DEBUG: "*"
      #     run:
      #       dir: source
      #       path: npm
      #       args: [test]
      - put: image
        params:
          build: source
