resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: source
    type: git
    icon: github-circle
    source:
      uri: git@github.com:petewall/wallhouse-ui.git
      branch: master
      private_key: ((github-repo-key))

  - name: image
    type: docker-image
    icon: docker
    source:
      repository: petewall/wallhouse-ui
      username: ((dockerhub-username))
      password: ((dockerhub-password))

  - name: pull-requests
    type: pull-request
    source:
      repository: petewall/wallhouse-ui
      access_token: ((github-access-token))

jobs:
  - name: build-image
    plan:
      - get: source
        trigger: true
      - task: deps
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: slim
          inputs:
            - name: source
          outputs:
            - name: source
          run:
            dir: source
            path: yarn
            args: [--emoji, install]
      - task: lint
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: slim
          inputs:
            - name: source
          run:
            dir: source
            path: yarn
            args: [--emoji, lint]
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: slim
          inputs:
            - name: source
          run:
            dir: source
            path: yarn
            args: [--emoji, test]
      - put: image
        params:
          build: source

  - name: test-pull-request
    plan:
      - get: source
        resource: pull-requests
        trigger: true
        version: every
        params:
          integration_tool: rebase
      - put: pull-requests
        params:
          path: source
          status: pending
      - task: deps
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: slim
          inputs:
            - name: source
          outputs:
            - name: source
          run:
            dir: source
            path: yarn
            args: [--emoji, install]
        on_failure:
          put: pull-requests
          params:
            path: source
            status: failure
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: slim
          inputs:
            - name: source
          run:
            dir: source
            path: yarn
            args: [--emoji, test]
        on_failure:
          put: pull-requests
          params:
            path: source
            status: failure
      - put: pull-requests
        params:
          path: source
          status: success
